# Generated by Django 3.2.16 on 2023-09-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_id',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
