# Generated by Django 3.2.16 on 2023-09-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
