# Generated by Django 3.2.16 on 2023-09-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
