# Generated by Django 4.1.2 on 2023-09-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
